language: ruby
install:
- bundle install
- npm install -g fis
- npm install -g fis-postpackager-simple@0.0.22
- npm install -g fis-optimizer-html-minifier
script: bundle exec rake site:deploy --quiet
branches:
  only:
  - master
cache:
- bundler
- npm
env:
  global:
    secure: ExxDy1CrZmrkE4rEVp9FGQxl/D+hmI9UcbFpCCAfLxGN1NnsgS5eDaLo2nS4++q+7GWWRDL/yex4xpfkMuQwAOpo+UL16XAkuyi/Lzs9jttdrfgeMnZMtOPv+YX9MiDHNlZXCK4zPFH1+3AEgSK4i0IjjF486wjVMKOQ3UPp+hU=
